version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: suitecrm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: suitecrmpassword
    volumes:
      - db_data:/var/lib/mysql

  suitecrm:
    image: bitnami/suitecrm:latest
    container_name: suitecrm-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SUITECRM_DATABASE_HOST=db
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_NAME=suitecrm
      - SUITECRM_DATABASE_USER=suitecrm
      - SUITECRM_DATABASE_PASSWORD=suitecrmpassword
      - SUITECRM_USERNAME=admin
      - SUITECRM_PASSWORD=admin123
      - SUITECRM_EMAIL=admin@example.com
    volumes:
      - suitecrm_data:/bitnami/suitecrm

volumes:
  db_data:
  suitecrm_data:
